language: node_js
node_js:
  - "8"
  - "10"

os:
  - osx
  - linux

sudo: false
cache:
  directories:
    - node_modules

script:
  - npm run coverage
  
  # run install script by removing /var
  # directory to make sure we catch error's regarding
  # /var directory not being present.
  - mv var _var
  - node scripts/install --non-interactive
  - mv _var var

after_success:
  - npm i codecov
  - nyc report --reporter=lcov > codecov.info && codecov
