language: node_js
node_js:
  - "8"
  - "10"

os:
  - osx
  - linux

sudo: required
cache:
  directories:
    - node_modules
    - ~/.cache/Cypress
    - ~/Library/Caches/Cypress

script:
  # runs tools/test-all
  - npm run coverage
  - npm i codecov nyc
  - nyc report --reporter=lcov > codecov.info && codecov

  # First run git clean -xdf to remove ignore file
  # and make the state similar to newly cloned repository
  - git clean -xdf
  - node scripts/install --non-interactive --startup
