language: node_js
node_js:
  - "8"
  - "10"

os:
  - osx
  - linux

sudo: required
cache:
  directories:
    - node_modules
    - ~/.cache/Cypress
    - ~/Library/Caches/Cypress

script:
  # runs tools/test-all
  - npm run coverage

  # run install script by removing /var
  # directory to make sure we catch error's regarding
  # /var directory not being present.
  - mv var _var
  - rm -rf node_modules
  - node scripts/install --non-interactive --startup
  - mv _var var 

after_success:
  - npm i codecov nyc
  - nyc report --reporter=lcov > codecov.info && codecov
